# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init <- function(dict_path) {
    invisible(.Call('_hyphenatr_init', PACKAGE = 'hyphenatr', dict_path))
}

#' Cleanup after ourselves
#'
#' @keywords internal
#' @export
cleanup <- function() {
    invisible(.Call('_hyphenatr_cleanup', PACKAGE = 'hyphenatr'))
}

#' Test to see if the hyphenation language rules dictionary is loaded
#'
#' @export
#' @note The \code{en_US} hyphenation rules dictionary is loaded by default
hyphendict_is_loaded <- function() {
    .Call('_hyphenatr_hyphendict_is_loaded', PACKAGE = 'hyphenatr')
}

hyphenate <- function(words) {
    .Call('_hyphenatr_hyphenate', PACKAGE = 'hyphenatr', words)
}

